### ISSUE TITLE
Errors not properly defined, I am not able to fix this error, trying to understand why it cant generate an ontology from my markdown txt file

### ISSUE THREAD

**Issue by OGsiji** [FalkorDB/GraphRAG-SDK#53]
kg_generator-1  | ERROR:kg_generator.knowledge_graph.generator:Failed to generate ontology: Failed to create ontology
kg_generator-1  | ERROR:kg_generator.knowledge_graph.generator:Error generating knowledge graph: Failed to generate ontology: Failed to create ontology
kg_generator-1  | Traceback (most recent call last):
kg_generator-1  |   File "/app/src/kg_generator/knowledge_graph/generator.py", line 84, in _generate_ontology
kg_generator-1  |     ontology = Ontology.from_sources(
kg_generator-1  |   File "/usr/local/lib/python3.10/site-packages/graphrag_sdk/ontology.py", line 58, in from_sources
kg_generator-1  |     return step.run(boundaries=boundaries)
kg_generator-1  |   File "/usr/local/lib/python3.10/site-packages/graphrag_sdk/steps/create_ontology_step.py", line 79, in run
kg_generator-1  |     raise Exception("Failed to create ontology")
kg_generator-1  | Exception: Failed to create ontology
kg_generator-1  | 
kg_generator-1  | During handling of the above exception, another exception occurred:
kg_generator-1  | 
kg_generator-1  | Traceback (most recent call last):
kg_generator-1  |   File "/app/src/kg_generator/knowledge_graph/generator.py", line 62, in generate_knowledge_graph
kg_generator-1  |     ontology = await self._generate_ontology(all_sources, kg_name)
kg_generator-1  |   File "/app/src/kg_generator/knowledge_graph/generator.py", line 99, in _generate_ontology
kg_generator-1  |     raise KnowledgeGraphError(f"Failed to generate ontology: {str(e)}")
kg_generator-1  | kg_generator.exceptions.KnowledgeGraphError: Failed to generate ontology: Failed to create ontology
kg_generator-1  | 
kg_generator-1  | During handling of the above exception, another exception occurred:
kg_generator-1  | 
kg_generator-1  | Traceback (most recent call last):
kg_generator-1  |   File "/app/examples/basic_usage.py", line 76, in <module>
kg_generator-1  |     asyncio.run(main())
kg_generator-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
kg_generator-1  |     return loop.run_until_complete(main)
kg_generator-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
kg_generator-1  |     return future.result()
kg_generator-1  |   File "/app/examples/basic_usage.py", line 53, in main
kg_generator-1  |     await kg_generator.generate_knowledge_graph(
kg_generator-1  |   File "/app/src/kg_generator/knowledge_graph/generator.py", line 67, in generate_knowledge_graph
kg_generator-1  |     raise KnowledgeGraphError(f"Failed to generate knowledge graph: {str(e)}")
kg_generator-1  | kg_generator.exceptions.KnowledgeGraphError: Failed to generate knowledge graph: Failed to generate ontology: Failed to create ontology
kg_generator-1  | WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
kg_generator-1  | E0000 00:00:1735207616.464104       1 init.cc:229] grpc_wait_for_shutdown_with_timeout() timed out.

**Comment by galshubeli** [comment]
Hi OGsiji,
Thank you for updating your issue.

Which model do you use?

I’d be happy to discuss it on Discord.

**Comment by galshubeli** [comment]
v1.0.0rc1 is a from-scratch rewrite that removes the v0.x APIs / code paths this issue references. Closing as no longer applicable. If you still see this behavior on v1 (installable with `pip install graphrag-sdk --pre`), please reopen with a v1 repro — see the [README](https://github.com/FalkorDB/GraphRAG-SDK) for the new shape.

v0.x code is preserved on the [`legacy-v0-main`](https://github.com/FalkorDB/GraphRAG-SDK/tree/legacy-v0-main) branch and the `v0-final` tag — no new v0 releases are planned.

**Comment by OGsiji** [comment]
ooh, thanks
